let items = [
    "Cabrio",
    "Phils Podcast",
    "Markus Podcast",
    "Star Wars Brettspiel",
    "Phils Penis",
    "Google Kalender",
    "Aufnahmetag",
    "Uhrzeit",
    "Knoppers Nussriegel",
    "Markus ist müde",
    "diZee Sprach- nachricht",
    "Mein Audacity ist abgestürzt",
    "Einer ist Gast",
    "Überleitung nicht geklappt",
    "Markus moderiert ab",
    "Phil moderiert ab",
    "Guthaben nachkaufen",
    "aber ähm",
    "war gewesen",
    "Phil leakt seine Daten ausversehen",
    "Shout out an meinen boi",
    "Markus macht den Stromberg",
    "Auf gewohnt gutem Niveau",
    "Konstitu- tionelle Monarchie",
    "Anderer Podcast wird thematisiert",
    "Livetour",
    "Patreon",
    "Künstlerische Freiheit",
    "Beziehungs- kram",
    "Es wird erzählt, was Donnerstag getan wird"
]